### ISSUE TITLE
Migrate issues from catalogueglobal repo

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#276]
Conveyal is moving active development of this codebase back to the conveyal repo. As part of this, we are migrating issues from https://github.com/catalogueglobal/datatools-ui and https://github.com/catalogueglobal/datatools-server to their respective repositories in the Conveyal GitHub organization.

We are using the https://github.com/IQAndreas/github-issues-import python script. Apologies to any watchers of this repo for excessive notifications.

**Comment by evansiroky** [comment]
Looks like this is only waiting on https://github.com/catalogueglobal/datatools-ui/pull/256 to be completed.
