### ISSUE TITLE
Add flow typing throughout app

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#290]
<a href="https://github.com/evansiroky"><img src="https://avatars1.githubusercontent.com/u/3112493?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [evansiroky](https://github.com/evansiroky)**
_Thursday May 31, 2018 at 21:22 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/181_

----

- [x] acitons
- [x] components
- [x] containers
- [x] reducers
- [x] util files
- [x] other

**Comment by landonreed** [comment]
<a href="https://github.com/evansiroky"><img src="https://avatars1.githubusercontent.com/u/3112493?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [evansiroky](https://github.com/evansiroky)**
_Wednesday Aug 22, 2018 at 22:12 GMT_

----

A [bug in flow](https://github.com/facebook/flow/issues/6782) is causing us to hold off on completely typing the reducers.

**Comment by landonreed** [comment]
<a href="https://github.com/evansiroky"><img src="https://avatars1.githubusercontent.com/u/3112493?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [evansiroky](https://github.com/evansiroky)**
_Monday Sep 17, 2018 at 19:53 GMT_

----

Actions are now flow-typed as of https://github.com/catalogueglobal/datatools-ui/commit/d9fb7d1cde8300a5a17fe89459fbc9c424e5992a!  🎊 🎉

**Comment by evansiroky** [comment]
It appears that there is no progress in the flow library on the issue preventing implementation of flow-typing reducers. I just encountered an error in a reducer that would've been prevented by proper flow-typing. I think we should just refactor the reducers to each have a function per action type so we can properly type each function with the corresponding action payload.

**Comment by evansiroky** [comment]
I refactored the admin users reducer here: https://github.com/conveyal/datatools-ui/commit/91e79b52d9507c311b3666a81877806787930621

It is definitely more boilerplate, but the flow typing works which I think would be worth it.

**Comment by binh-dam-ibigroup** [comment]
Closing this issue because all items in the checklist are complete.
