### ISSUE TITLE
Authentication broken for safari

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#335]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [landonreed](https://github.com/landonreed)**
_Tuesday Jul 24, 2018 at 14:38 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/226_

----

It appears that [cross-origin authentication](https://auth0.com/docs/cross-origin-authentication) is broken for safari. Steps to recreate:

1. Open localhost in safari
2. Attempt to log in
3. `authorize` request to Auth0 fails (page will not load).

It looks like this authorize endpoint is also failing in other browsers (e.g. Chrome), but it does not have the effect of locking the user out.

**Comment by evansiroky** [comment]
Bumping this. I'm unable to login with MacOS 10.14.5, Chrome/74.0.3729.169 both locally and on the latest dev site. I keep getting the error:

`Failed cross origin authentication`
`Unable to configure verification page.`

Oddly enough, my old computer (MacOS 10.13.1, Chrome/74.0.3729.157) is able to login.

Local datatools-server: https://github.com/ibi-group/datatools-server/commit/6b36529d953d2eab2c55b75776878453b1a452ef
Local datatools-ui: https://github.com/ibi-group/datatools-ui/commit/b75e7d2669d060b016a77b191bc15fc80d7fa489
Auth0 client id: dR7G....fTe

**Comment by daniel-heppner-ibigroup** [comment]
Looks like this is still broken on MacOS 12.1, Safari 15.2.
