### ISSUE TITLE
Deploy to R5

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#343]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [landonreed](https://github.com/landonreed)**
_Tuesday Aug 07, 2018 at 14:48 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/234_

----

Add option to deploy to servers running R5 (in addition to the currently supported OTP servers).

This would likely be done by starting up a new EC2 server with instructions to download a specific R5/OTP version plus the relevant GTFS feeds and OSM data and kick off the application.  This requires adding user data similar to the [R5 worker script](https://github.com/conveyal/r5/blob/dev/src/main/resources/worker.sh).

**Comment by binh-dam-ibigroup** [comment]
Closing this issue. R5 deployments are no longer supported since #519 and #638.
