### ISSUE TITLE
Turn by turn API call service

### ISSUE THREAD

**Issue by a1ex4nd3r** [ibi-group/datatools-ui#383]
This issue states that only Graphhopper is available currently for turn by turn api calls #166 . Correct me if I am wrong. Is it possible to use another service like OSRM for turn by turn API calls?

**Comment by landonreed** [comment]
Currently, the application is only set up to use Graphhopper for creating snapped-to-street geometries for trip patterns. It likely is possible to use some other service, but we have not configured the application for alternative services and I think we're somewhat wary of introducing alternatives because of any increased complexity in the already complicated pattern shape manipulation/creation.

**Comment by wkulesza** [comment]
@landonreed Is Graphhopper open-source (hosted on own servers) also supported, or only the hosted version of Graphhopper (paid plans?)

**Comment by landonreed** [comment]
Graphhopper open-source is not currently supported, but I think this would be a relatively simple fix. I think we would just need to make the URL [in this request](https://github.com/catalogueglobal/datatools-ui/blob/79d8bbec1cef4e060e13ad58387605db5183e0f3/lib/scenario-editor/utils/valhalla.js#L218) come from a config variable from `env.yml` (similar to `GRAH_HOPPER_KEY`).

**Comment by wkulesza** [comment]
@landonreed Hi, we would be ready to submit PR for this (done already by @a1ex4nd3r ) but we noticed this is linked to another issue #385 - and this indirectly blocks the full functionality - once gtfs without shapes is imported, shapes are then generated using open-source Graphhopper or indeed commercial Graphhopper and then such gtfs with shapes is exported, the zip file doesn't include the shapes.txt file at all). Is there anyone working on it ?

**Comment by landonreed** [comment]
@wkulesza, I had noticed your question was unanswered when going through old issues today. #385 has in fact been closed, but I'm not sure if you still need this functionality. Let me know if this is no longer needed and I will close (otherwise, still happy to accept a PR!).
