### ISSUE TITLE
Add indicator showing various diffs (# issues, # routes, # trips) from previous version

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#384]
## Issue
It is difficult to understand how a new feed version has changed from a previous feed version. This includes how the service has changed (# of routes, trips, etc.) and how the feed quality has changed (number and type of issues).

## Solution
We are adding the ability to compare two feed versions to quickly reveal to the user what has changed between versions of GTFS. The user will see indications in the UI of whether # of validation issues and counts of agencies, routes, stops, trips, stop times have decreased, increased, or remained the same over the previous version.

For validation issues, this indicator could be placed next to the issue count in the tabs at the left of the version summary.

Having a diff for the number of entities found in the feed (e.g., `+1000 trips` vs. the previous version) would also be very helpful.

### What we want to accomplish:

- [ ] When you select a feed version, then automatically compare to the previous version. Keep the views as they are.
- [ ] We want to offer to compare to another version. (do we want to limit to just a previous version?)
  - [ ] Add a drop-down selector, next to the version selector, that will refer to the compared version (displays [same contents as version selector -or- certain versions only]).
![image](https://user-images.githubusercontent.com/56846598/69666713-b059d600-105a-11ea-9b80-e3027992069b.png)

- ~[ ] In summary row, also display the count of validation issues as a stat.~
- [ ] In summary tab, display ~an up or down arrow~ +/- sign to indicate the change vs the other version for all of the stats. ~Underneath, display the actual change (e.g. `5 new`, `2 deleted`).~
![image](https://user-images.githubusercontent.com/56846598/69666873-fd3dac80-105a-11ea-9182-547fa2fba5bd.png)

- [ ] Display the change in validation errors on the left hand panel.
![image](https://user-images.githubusercontent.com/56846598/69667459-0f6c1a80-105c-11ea-9ad3-8e4fe37d2461.png)

### For Later

* Display the actual number of additions and deletions (requires backend change).
* For agency, routes, and stops, show which ones were added/removed in a popup when you click on the stat (requires backend change).
* For days active, figure out how to convey the changes, e.g.
```
| aaaaa______ |
| ___bbbbbb__  |
```

**Comment by binh-dam-ibigroup** [comment]
Open questions:

* Styling of UI shown in screenshots in description?
* Offer to compare to older and newer versions, or just older versions?
* Other desired behaviors not captured?
