### ISSUE TITLE
Unable to install mastarm 

### ISSUE THREAD

**Issue by syeda25** [ibi-group/datatools-ui#439]
Hello Everyone,
I am trying to setup datatools-ui in my local system. Mastarm is not installing it cause error .Please guide me how can I install mastram and configure it with datatools-ui.

![mastarm-error](https://user-images.githubusercontent.com/8528805/58010373-abdfbe00-7b09-11e9-9fa7-20fb6eb5e311.PNG)

**Comment by landonreed** [comment]
Looks like you might need `git` installed on your machine. Unfortunately, we don't use Windows, so we can't offer much advice on that front.
