### ISSUE TITLE
Edited pattern attributes does not survive across feed versioning

### ISSUE THREAD

**Issue by aguiraf** [ibi-group/datatools-ui#454]
## Observed behavior
When a new version is created from a snapshot all patterns are recreated from trips, so all modified pattern attributes (e.g. pattern name) are lost.

## Expected behavior
If I change the pattern name in the editor I expect that, creating a new version, the pattern name is still there as written by me.

## Steps to reproduce the problem
- select a route in the editor
- modify the name of a pattern
- make a snapshot 
- publish the snapshot as a new version
- find the route in the manager
- there is no pattern with the modified name (all patterns are recreated)

## Any special notes on configuration used
none

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

last commit in dev branch for both server and ui

**Comment by landonreed** [comment]
Unfortunately, the pattern object is not a part of the GTFS specification. As a rule, we generally try not to export editor-specific tables or fields into output GTFS.
