### ISSUE TITLE
Auth0 - access_denied: Invalid state

### ISSUE THREAD

**Issue by xrestinpieces** [ibi-group/datatools-ui#461]
## Observed behavior
Hello,

After following the latest [guide ](https://conveyal-data-tools.readthedocs.io/en/latest/dev/deployment/) for deployment I am still not able to login with Auth0 even after the recent update of the server. I am simply trying to deploy the application for testing purposes but even after I tried with both s3 bucket and localhost I am getting this error:

### Web output:

![image](https://user-images.githubusercontent.com/24899524/62430967-eda4fb80-b72b-11e9-84e4-83c5cbacf9f8.png)

### Console log:

![image](https://user-images.githubusercontent.com/24899524/62430647-1b884100-b728-11e9-8b75-6835b97fb4b3.png)

### Debug output:

![image](https://user-images.githubusercontent.com/24899524/62430836-67d48080-b72a-11e9-8842-74dddcdfa855.png)

After login button is pressed Winchan opens a different browser window (as it should) and shuts down after 1-2 seconds. The URL that I managed to capture (edited for clarification):

- https://<auth0_domain>.eu.auth0.com/sso_dbconnection_popup/<auth0_client_id>

which seems correct based on the auth0-js file 

![image](https://user-images.githubusercontent.com/24899524/62431108-4f199a00-b72d-11e9-846c-e29c0e312e02.png)

The procedure was done very carefully so I don't believe I missed something in the process but something is breaking the state value that auth0-lock.js sees. State is only passed as argument in 
Auth0Manager.js:85:22 with value the URL of the current window that called the login.

Any help would be greatly appreciated

## Expected behavior

Simple login

## Steps to reproduce the problem

Even the guide is outdated on some parts (regarding Auth0 setup) you just have to follow the process described in Read The Docs and just add 2 Auth0 applications (one REGULAR WEB APPLICATION and one MACHINE-TO-MACHINE)

## Any special notes on configuration used

Updated version of env.yml (server) contains 2 new entries which refer to the MTM application:

- AUTH0_API_CLIENT
- AUTH0_API_SECRET

The rest are filled as described in the latest documentation.

**Comment by landonreed** [comment]
Unfortunately, Auth0 issues can be difficult to diagnose. I don't believe this is a bug, but looks to be a misconfigured application. Elaborating on which other Auth0 config variables you have set in both the UI and server may help us diagnose. 

However, as a first crack, you may want to try logging in with an updated version of Chrome -- some browsers can experience issues with logging in.
