### ISSUE TITLE
Avoid Auth0

### ISSUE THREAD

**Issue by toton6868** [ibi-group/datatools-ui#480]
I do not want to use the Auth0 and I have put in server `env.yml`

`DISABLE_AUTH: true`

Then I am starting the server using 
```
npm i
npm start
```

When I am accessing http://0.0.0.0:9967/ it always asking for login. Auth0 is too much pain and hectic. Do not want to use it. what should I do?

**Comment by danielhep** [comment]
Also wondering this.

**Comment by landonreed** [comment]
As @typhoon2099 noted in #177, the `DISABLE_AUTH` environment variable for the UI is no longer used anywhere in the code, so it is currently not possible to circumvent Auth0. We don't have any plans at the moment to add this back in, but will update this ticket if that changes. Apologies for those looking to avoid Auth0. I know it can be a pain to set up, but once it has been setup it should be relatively smooth sailing.

**Comment by markusstraub** [comment]
It would be great if you could update the documentation to reflect this change, https://data-tools-docs.ibi-transit.com/en/latest/dev/deployment/ still says:

>  If you don't need authentication (e.g., if you're running locally or on a secured network), you can set DISABLE_AUTH to true for both the server and UI configurations
