### ISSUE TITLE
Renew Auth appears to be broken for new Auth0 tenants

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#482]
## Observed behavior (please include a screenshot if possible)

When a browser tab has remained open overnight and the auth token has expired, reloading the web page causes the page to appear frozen on a blank page. It appears that the renewAuth function is erroring out:

https://github.com/ibi-group/datatools-ui/blob/dfa01a0c21dbc5de8e5b9dc89471700a30759823/lib/common/user/Auth0Manager.js#L362-L389

## Expected behavior

On page reload, the expired token should trigger a token renewal and the web page should reload normally.

## Steps to reproduce the problem

Run localhost server with localhost configuration. Allow token to expire (perhaps to expedite this for testing, the token expiration time can be shortened via the Auth0 console). Reload web page.

## Any special notes on configuration used

localhost config. May need to modify token expiration time to reproduce.

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

Running latest commites for `deploy-to-ec2` branches, but I believe this also exists in latest `dev`.

**Comment by evansiroky** [comment]
The localhost callback urls weren't setup correctly. I have changed this in the Auth0 management profile. Please re-open if this is still a problem.
