### ISSUE TITLE
MTC Enhancements 03/2020

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#544]
- [x] Update feed version dropdown (reverse sort, retrieval method filtering)
- [x] Add field length validation checks (per requirements set forth in [511 Transit_Data Guidelines_V2.0](https://github.com/ibi-group/datatools-ui/files/4438625/511.Transit_Data.Guidelines_V2.0_3-27-2020.pdf))
- [x] Add ability to transform GTFS feeds, including:
  - [x] Replace file (e.g., `stop_attributes.txt`) in new version with file from previous version)
  - [x] Replace file in new version with user-defined CSV data

**Comment by binh-dam-ibigroup** [comment]
Closing this issue, the transformations were handled by #579, field length validation in #648.
