### ISSUE TITLE
Add date range selector for schedule exceptions in Editor

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#549]
Currently when creating a schedule exception in the GTFS Editor, if the exception is intended to last for an extended period, each date must be added individually, which can be very tedious for any exception lasting over a week. We should replace the individual dates with a range selector (perhaps https://www.npmjs.com/package/react-date-range?).

![image](https://user-images.githubusercontent.com/2370911/78256616-c6731980-74c6-11ea-90bf-eecdaf0ed4b8.png)

**Comment by binh-dam-ibigroup** [comment]
Closed by #828.
