### ISSUE TITLE
Creating an attributions.txt file

### ISSUE THREAD

**Issue by Abramovick** [ibi-group/datatools-ui#608]
## Observed behavior
The UI doesn't offer a way to create inputs for an `attributions.txt` file.

Any plans to support this in the future releases?

**Comment by landonreed** [comment]
Hi @Abramovick, we have no plans to add editing/validation for the `attributions.txt` file at the moment.

**Comment by Abramovick** [comment]
@landonreed I'll raise a PR to include that feature soon then.
