### ISSUE TITLE
Editor: Show routes on a map causes out of memory issues

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#627]
## Observed behavior (please include a screenshot if possible)

In the editor, turning on the pattern shapes overlay will cause out of memory issues for very large feeds.

## Expected behavior

There is currently no back end solution to prevent this, so this feature ought to be disabled for now.

## Steps to reproduce the problem

1. Open the editor for a very large feed
2. In the top left corner of the map check the 'Show routes on map' overlay
3. A massive GraphQL query requests the shape points for every pattern and kills the application

## Any special notes on configuration used

N/A

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

latest dev

**Comment by binh-dam-ibigroup** [comment]
Reopening this issue after merging #628 per https://github.com/ibi-group/datatools-ui/pull/628#pullrequestreview-537816225 by @evansiroky.
