### ISSUE TITLE
Change project selector UI to React Select

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#650]
The current project selector on the home page is somewhat cumbersome to use when a user has access to many projects. Also, the "Create Project" option is at the very bottom of the dropdown, which makes for quite a chore to create a new project.

### Approach
- [ ] Replace the bootstrap DropdownButton for the selector with a React Select dropdown so that users can begin typing the project name and select an item more quickly.
- [ ] Remove entirely the "Manage Projects" option (it links to an unrelated page)
- [ ] Remove the "Create Project" option and instead replace with a New Project button to the right of the selector

### Current Selector UI
![image](https://user-images.githubusercontent.com/2370911/112031391-a8f0f280-8b11-11eb-9f32-3930c7e770fc.png)

### Mockup of new Approach
TODO

**Comment by binh-dam-ibigroup** [comment]
I think the dropdown + button combo should be replaced with a project table that could be shown in the main area of the screen as opposed to the side.

**Comment by robertgregg3** [comment]
@binh-dam-ibigroup  That would be good. What would normally go in the "Recent Activity section"?  Perhaps that can be moved to the sidebar depending on the importance.
