### ISSUE TITLE
Feature request: have the ability to advance all feed sources to their latest version in a deployment configuration

### ISSUE THREAD

**Issue by evansiroky** [ibi-group/datatools-ui#652]
## Observed behavior (please include a screenshot if possible)

It takes FOREVER to advance all feed versions in a deployment to their latest versions.

## Expected behavior

It would be really nice if there was a single button to advance all feed sources to their latest version at once. Also, it would be great if each individual feed source had an advance to latest button.

## Steps to reproduce the problem

Try updating every single feed source in a large deployment.

## Any special notes on configuration used

n/a

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

https://github.com/conveyal/datatools-ui/commit/d91be65ba07d337e36ce746d2ca6a820bab15ef8

**Comment by binh-dam-ibigroup** [comment]
Closing this issue, it is fixed by #637.
