### ISSUE TITLE
i18n polish language ?

### ISSUE THREAD

**Issue by wkulesza** [ibi-group/datatools-ui#695]
We would like to add to i18n of the ui. Providing we create a polish.yml file, what happens next in order to have the UI in polish ?

**Comment by wkulesza** [comment]
Any hints on that @landonreed @abyrd. Is l18n configurable in the config files ?

**Comment by landonreed** [comment]
Hi @wkulesza, the framework for i18n is mostly in place, but there are quite a few messages throughout the web app that have not been captured in the current `english.yml` file. So, when you add the `polish.yml` file there will likely be a significant amount of work to locate and replace those hard-coded english messages with fields in the yml files.

Beyond that, as long as the user's browser language is set to Polish it should work out of the box! This check in `config.js` for `languageId` will default to the user's preferred language (`navigator.language`): https://github.com/ibi-group/datatools-ui/blob/c6bffda74320c450a19b7e10c382e09c6f51c279/lib/common/util/config.js#L119-L121

**Comment by wkulesza** [comment]
@landonreed hi, thanks for pointers.
I'm using my fork (https://github.com/wkulesza/datatools-ui)  with polish.yml in i18n folder - my chrome browser is in polish locale, but still seeing only english language.
Any pointers ?

**Comment by landonreed** [comment]
I think you also may need to add the polish file here: https://github.com/ibi-group/datatools-ui/blob/c6bffda74320c450a19b7e10c382e09c6f51c279/lib/common/util/config.js#L101-L102

**Comment by wkulesza** [comment]
Hi,
added this to config.js

https://github.com/wkulesza/datatools-ui/blob/782d73679e92daf0cda9dca0c008259a14f2921f/lib/common/util/config.js#L100-L101

re-started, but it wasn't picked up by data tools ui. Obviously added that polish.yml file to where the english.yml resides (and checked its validity).

**Comment by wkulesza** [comment]
@landonreed Hi Landon,
i only left this line:
```
require('../../../i18n/english.yml')
```
and replaced english with polish (of course the file polish.yml is located in that directory), then brought up the dockers and still, i can only see english version.

**Comment by landonreed** [comment]
Hi @wkulesza, unfortunately I'm no longer regularly involved with this project, but I'm sure @binh-dam-ibigroup might be able to help you out!
