### ISSUE TITLE
Error login on yarn start call

### ISSUE THREAD

**Issue by dancesWithCycles** [ibi-group/datatools-ui#771]
## Observed behavior (please include a screenshot if possible)

I am running datatools-server latest version ```4.1.0``` like this.

```
java -jar target/dt-v3.2.0-1515-gb119c30.jar configurations/default/env.yml configurations/test/server.yml
```

I disabled authentication like this.

```
begerad@ltpt490:~/git/ibi-group/datatools-server$ cat configurations/default/env.yml
# This client ID refers to the UI client in Auth0.
AUTH0_CLIENT_ID: your-auth0-client-id
AUTH0_DOMAIN: your-auth0-domain
# Note: One of AUTH0_SECRET or AUTH0_PUBLIC_KEY should be used depending on the signing algorithm set on the client.
# It seems that newer Auth0 accounts (2017 and later) might default to RS256 (public key).
AUTH0_SECRET: your-auth0-secret # uses HS256 signing algorithm
# AUTH0_PUBLIC_KEY: /path/to/auth0.pem # uses RS256 signing algorithm
# This client/secret pair refer to a machine-to-machine Auth0 application used to access the Management API.
AUTH0_API_CLIENT: your-api-client-id
AUTH0_API_SECRET: your-api-secret-id
DISABLE_AUTH: true
OSM_VEX: http://localhost:1000
SPARKPOST_KEY: your-sparkpost-key
SPARKPOST_EMAIL: email@example.com
GTFS_DATABASE_URL: jdbc:postgresql://localhost/sib00_vbn_gtfs
GTFS_DATABASE_USER: sib00_vbn_gtfs
GTFS_DATABASE_PASSWORD: #lostInUsa21
#MONGO_HOST: mongo-host:27017
MONGO_DB_NAME: ibi-app-storage
```
I am using the test settings provided by the repository.

I am calling datatools-ui latest release version ```4.1.0``` like this.

```
begerad@ltpt490:~/git/ibi-group/datatools-ui$ nvm use v10.12.0
Now using node v10.12.0 (npm v6.4.1)
begerad@ltpt490:~/git/ibi-group/datatools-ui$ node -v
v10.12.0
begerad@ltpt490:~/git/ibi-group/datatools-ui$ npm -v
6.4.1
begerad@ltpt490:~/git/ibi-group/datatools-ui$ npm i -g yarn

> yarn@1.22.17 preinstall /home/begerad/.nvm/versions/node/v10.12.0/lib/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

/home/begerad/.nvm/versions/node/v10.12.0/bin/yarnpkg -> /home/begerad/.nvm/versions/node/v10.12.0/lib/node_modules/yarn/bin/yarn.js
/home/begerad/.nvm/versions/node/v10.12.0/bin/yarn -> /home/begerad/.nvm/versions/node/v10.12.0/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.17
added 1 package in 0.774s
begerad@ltpt490:~/git/ibi-group/datatools-ui$ yarn -v
1.22.17
begerad@ltpt490:~/git/ibi-group/datatools-ui$ yarn
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.77s.
begerad@ltpt490:~/git/ibi-group/datatools-ui$ yarn start
yarn run v1.22.17
$ yarn
[1/4] Resolving packages...
success Already up-to-date.
$ mastarm build --env dev --serve --proxy http://localhost:4000/api
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
[0001] info  Server running at http://192.168.178.50:9966/ (connect)
[0012] 40ms          0B GET    304 /
[0012] 16ms          0B GET    304 /dist/index.css
updated dist/index.css
updated dist/index.css
[0032] 31.3s       25MB (browserify)
[0032] 20.7s         0B GET    200 /dist/index.js (middleware)
[0034] 54ms        919B GET    200 /api/manager/public/appinfo (middleware)
[0050] 1ms         569B GET    200 /
[0050] 0ms           0B GET    200 /dist/index.js (middleware)
[0065] 7ms         919B GET    200 /api/manager/public/appinfo (middleware)
```
You can see in the screenshot that I still have to login and that it is not working.

![Screenshot_2022-03-16_11-05-41](https://user-images.githubusercontent.com/47819327/158566985-d1642f6a-a6ab-423d-b13e-399e257c9020.png)

## Expected behavior

I would like to test a setup where I do not have to login using disabled authentication.

## Steps to reproduce the problem

Please refer to the setup above.

## Any special notes on configuration used

Please refer to the configuration above.

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

I am using datatools-server and datatools-ui latest release version ```4.1.0```.

I thank you  very much for providing and maintaining this repository and appreciate any help.

Cheers,

Stefan

**Comment by dancesWithCycles** [comment]
Disabling the authentication is also not working with the instruction

```
yarn start --config configurations/default/env-da-vbn-gtfs.yml
```

loading the following configuration.

```
cat configurations/default/env-da-vbn-gtfs.yml
AUTH0_CLIENT_ID: your-auth0-client-id
AUTH0_DOMAIN: your-auth0-domain
DISABLE_AUTH: true
BUGSNAG_KEY: optional-bugsnag-key
MAPBOX_ACCESS_TOKEN: your-mapbox-access-token
MAPBOX_MAP_ID: mapbox/outdoors-v11
MAPBOX_ATTRIBUTION: <a href="https://www.mapbox.com/about/maps/" target="_blank">&copy; Mapbox &copy; OpenStreetMap</a> <a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a>
SLACK_CHANNEL: optional-slack-channel
SLACK_WEBHOOK: optional-slack-webhook
GRAPH_HOPPER_KEY: your-graph-hopper-key
# Optional override to use a custom service instead of the graphhopper.com hosted service.
# GRAPH_HOPPER_URL: http://localhost:8989/
GOOGLE_ANALYTICS_TRACKING_ID: optional-ga-key
# GRAPH_HOPPER_POINT_LIMIT: 10 # Defaults to 30
```

I appreciate any hint in the right direction.

Cheers,

Stefan

**Comment by miles-grant-ibigroup** [comment]
I believe `DISABLE_AUTH` isn't quite working at the moment. We can try to look more into this, but aren't always able to get to every issue in a timely manner.

We do however welcome PRs and I would be happy to review any PR that helps fix this functionality! If you go this route, you might want to start by looking here: https://github.com/ibi-group/datatools-ui/blob/4e7b8eac69fd14ae40b8a13ea86c3bf8b5e44691/lib/common/user/Auth0Manager.js

**Comment by miles-grant-ibigroup** [comment]
See https://github.com/ibi-group/datatools-ui/issues/480#issuecomment-549454520

**Comment by dancesWithCycles** [comment]
Hi @miles-grant-ibigroup ,
Thank you so much for the hint and the links. I'll let you know, when I have a working solution without using authentication.

Cheers,

Stefan

**Comment by dancesWithCycles** [comment]
Hi @miles-grant-ibigroup ,
From reading older issues #177 and #480 it sounds like DISABLE_ATH worked in a past release or version. Is that right? Can you come up with a release or  version where DISABLE_ATH was working?

Cheers,

Stefan

**Comment by miles-grant-ibigroup** [comment]
I don't think any builds in this repo support it. If you check the old conveyal repo you may have some luck!

**Comment by mir-abdullah** [comment]
@miles-grant-ibigroup is this issue fixed or not?

**Comment by miles-grant-ibigroup** [comment]
If auth0 is configured correctly, login will work when using the latest `dev`.

The `DISABLE_AUTH` flag does not currently work. 

I hope this is helpful! Please let me know if you have any questions

**Comment by dancesWithCycles** [comment]
Thank you so much @miles-grant-ibigroup for making that crystal clear. I leave it up to you to open a new issue about the `DISABLE_AUTH` switch.

Cheers!

**Comment by mir-abdullah** [comment]
> If auth0 is configured correctly, login will work when using the latest `dev`.
> 
> The `DISABLE_AUTH` flag does not currently work.
> 
> I hope this is helpful! Please let me know if you have any questions

hi @miles-grant-ibigroup can you please guide me a bit on the process on where to make the account and where to feed the values of the account .
Any  help would be appreciated.
thankyou

**Comment by miles-grant-ibigroup** [comment]
@mir-abdullah Let me know how you get on with the instructions at https://data-tools-docs.ibi-transit.com/en/latest/dev/deployment/

If you have any trouble with them please let me know and we can try to debug together!

**Comment by dimacv** [comment]
Is this issue fixed ?

**Comment by miles-grant-ibigroup** [comment]
We are working to make the `DISABLE_AUTH` config item function correctly
