### ISSUE TITLE
Export Stops Failed with Firefox Browser

### ISSUE THREAD

**Issue by dancesWithCycles** [ibi-group/datatools-ui#822]
Hi folks,
Thank you so much for providing and maintaining this repository! I observed the following situation.

## Observed behavior

After selecting a feed, choosing the `Export` button and selecting `Stops`, Firefox replies with the following message.

```
/tmp/mozilla_begerad0/PLs_8nnQ.zip.part could not be saved, because the source file could not be read.

Try again later, or contact the server administrator.
```

I observed the same behavior for the `Routes` export.

![Screenshot_2022-07-21_11-48-28](https://user-images.githubusercontent.com/47819327/180185886-c12e2668-caef-426e-846d-2df929b21c41.png)

## Expected behavior

I expected the UI to export and download `Stops`.

## Steps to reproduce the problem

Please follow my description above with Firefox version ```91.10.0esr (64-bit)```

## Any special notes on configuration used

No notes.

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

Clicking on `Settings` in the sidebar reveals the following.

```
UI Version: | 496f5d
-- | --
UI deployed at: | July 12, 2022 4:40 AM
Server version: | d5aeef

UI Version:	[496f5d](https://github.com/ibi-group/datatools-ui/commit/496f5d580238906b97b096d92da7224fb5103c39)
UI deployed at:	July 12, 2022 4:40 AM
Server version:	[d5aeef](https://github.com/ibi-group/datatools-server/commit/d5aeef000a826561d48a4168582517ac5b62df34)
```
Cheers!

**Comment by miles-grant-ibigroup** [comment]
Thanks for the bug report! Always appreciated. 

@philip-cline I believe you have a fix for this in the works, right?

**Comment by philip-cline** [comment]
Hi @dancesWithCycles, this is fixed by https://github.com/ibi-group/datatools-server/pull/476. I'll update here when we've deployed update

**Comment by philip-cline** [comment]
This should be fixed now!
