### ISSUE TITLE
Error creating pattern shapes using 'From stops'

### ISSUE THREAD

**Issue by alixchaudhry** [ibi-group/datatools-ui#825]
## Observed behavior (please include a screenshot if possible)

Upon creating a route shape pattern by clicking the option of 'From Stops', the following error is generated.

![image](https://user-images.githubusercontent.com/82599266/180644810-390cbb8d-3fca-4c23-81b0-75f63b16ae9c.png)

## Expected behavior

It should snap to streets and create a proper shape pattern as it was previously doing. It worked perfectly a few weeks back.

## Steps to reproduce the problem

1. Create any route
2. Create the trip pattern by adding the stops in order of the journey.
3. Click 'From stops' button to generate shape.
![image](https://user-images.githubusercontent.com/82599266/180644872-ab03d399-61c4-4782-9f2b-4405e3b9b9b7.png)
4. Click 'OK' button to confirm creating the shape.
![image](https://user-images.githubusercontent.com/82599266/180644899-2f9125f0-aeb4-4d94-b73f-ef828b261fcd.png)
5. The Error is displayed.

## Any special notes on configuration used

None.

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

![image](https://user-images.githubusercontent.com/82599266/180644928-4a5cb553-7e16-4028-b2d7-30466337501c.png)

**Comment by miles-grant-ibigroup** [comment]
Thanks for the bug report! It's always appreciated. 

We have a PR in the works (#826) which addresses this. If you'd prefer not to deal with unmerged experimental branches, this PR should be merged into dev soon and I'll let you know when it is.

**Comment by afconlab** [comment]
hello @miles-grant-ibigroup i  have this issue with v5.0.0 
my graphopper key is set but it seems these is no request to graphopper.com site 

UI Version: | 0af605
-- | --
UI deployed at: | April 30, 2024 12:02 PM
Server version: | 8889e0

About this app
UI Version:	[0af605](https://github.com/ibi-group/datatools-ui/commit/0af6058348a93600cebb58a85126878d387bb4ed)
UI deployed at:	April 30, 2024 12:02 PM
Server version:	[8889e0](https://github.com/ibi-group/datatools-server/commit/8889e04911c89baa5fdce55610f14ba779f89a5e)

**Comment by miles-grant-ibigroup** [comment]
> hello @miles-grant-ibigroup i have this issue with v5.0.0 my graphopper key is set but it seems these is no request to graphopper.com site
> 
> UI Version:	0af605
> UI deployed at:	April 30, 2024 12:02 PM
> Server version:	8889e0
> About this app UI Version: [0af605](https://github.com/ibi-group/datatools-ui/commit/0af6058348a93600cebb58a85126878d387bb4ed) UI deployed at: April 30, 2024 12:02 PM Server version: [8889e0](https://github.com/ibi-group/datatools-server/commit/8889e04911c89baa5fdce55610f14ba779f89a5e)

Hi thanks for writing! Are you seeing any errors in your browser console?

**Comment by afconlab** [comment]
@miles-grant-ibigroup 
![pattern](https://github.com/ibi-group/datatools-ui/assets/150699416/d903b999-dc6b-45a3-ab7f-1edc025b635d)
I have this , when i try to add stop to the trip patterns

```
An error was encountered while trying to save to the database

Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isNull()" because the return value of "java.util.List.get(int)" is nullNetwork error (500)!

(put request on /api/editor/secure/pattern/2?feedId=08eb4bf1-524b-4776-99ef-ffa8ff5e1dc8&sessionId=node0uu2xy4rouq3c5htli8twqpi3)


```

**Comment by miles-grant-ibigroup** [comment]
Do you have server logs? This appears to be a server side issue

**Comment by afconlab** [comment]
@miles-grant-ibigroup 
avery request from /api/editor/secure/pattern/2 failled

![pattern](https://github.com/ibi-group/datatools-ui/assets/150699416/d1c8fa4c-b842-4a99-9054-47144ba5d47e)

if i try to access to 

`http://10.20.1.201:9966/api/editor/secure/pattern/2?feedId=08eb4bf1-524b-4776-99ef-ffa8ff5e1dc8&sessionId=node01ezj5ulqddtxuc7mzrv92p8z76`

I have this
`{"result":"ERR","message":"Authorization header is missing.","code":401,"detail":null}`
my auth0 log, i added url below on url allowed but i still have the same error


**below log from auth0**
"oauthError": "Callback URL mismatch. http://10.20.1.201:9966/feed/08eb4bf1-524b-4776-99ef-ffa8ff5e1dc8/edit/route/1/trippattern/2 is not in the list of allowed callback URLs. Please go to 'https://manage.auth0.com/#/applications/Z03hpM8afE56BCQXmO9ooP1lKQ0Q0PYZ/settings' and make sure you are sending the same callback url from your application.",

![pattern](https://github.com/ibi-group/datatools-ui/assets/150699416/3b06ddd2-7e45-485d-88a1-30f7a7c8bee5)

**log from server** 
> `INFO  2024-05-01T15:17:04.635 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:188) select use_frequency from hsnp_knopvddreipjhvdjmdbsnb.patterns where pattern_id = 'qb73'
> INFO  2024-05-01T15:17:04.637 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:1598) select shape_id from hsnp_knopvddreipjhvdjmdbsnb.patterns where id = 2
> INFO  2024-05-01T15:17:04.638 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:570) select id from hsnp_knopvddreipjhvdjmdbsnb.patterns where shape_id = 'wg9s'
> INFO  2024-05-01T15:17:04.640 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:739) delete from hsnp_knopvddreipjhvdjmdbsnb.shapes where shape_id = 'wg9s'
> INFO  2024-05-01T15:17:04.641 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:741) Deleted 0 shapes
> INFO  2024-05-01T15:17:04.643 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:683) Executing batch insert (0/0) for hsnp_knopvddreipjhvdjmdbsnb.shapes
> INFO  2024-05-01T15:17:04.643 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:690) No inserts to execute. Empty array found in JSON for child table hsnp_knopvddreipjhvdjmdbsnb.shapes
> INFO  2024-05-01T15:17:04.644 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:188) select use_frequency from hsnp_knopvddreipjhvdjmdbsnb.patterns where pattern_id = 'qb73'
> INFO  2024-05-01T15:17:04.645 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:1598) select pattern_id from hsnp_knopvddreipjhvdjmdbsnb.patterns where id = 2
> INFO  2024-05-01T15:17:04.649 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:960) Reconciling pattern stops for pattern ID=qb73
> INFO  2024-05-01T15:17:04.649 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:966) select stop_id from hsnp_knopvddreipjhvdjmdbsnb.pattern_stops where pattern_id = 'qb73' order by stop_sequence
> INFO  2024-05-01T15:17:04.651 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:739) delete from hsnp_knopvddreipjhvdjmdbsnb.pattern_stops where pattern_id = 'qb73'
> INFO  2024-05-01T15:17:04.652 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:741) Deleted 0 pattern_stops


**> ERROR 2024-05-01T15:17:04.655 [qtp1391483214-22] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:248) Error updating patterns entity
> java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isNull()" because the return value of "java.util.List.get(int)" is null
> 	at com.conveyal.gtfs.loader.JdbcTableWriter.updateLinkedFields(JdbcTableWriter.java:344)
> 	at com.conveyal.gtfs.loader.JdbcTableWriter.updateChildTable(JdbcTableWriter.java:635)
> 	at com.conveyal.gtfs.loader.JdbcTableWriter.update(JdbcTableWriter.java:194)
> 	at com.conveyal.datatools.editor.controllers.api.EditorController.update(EditorController.java:499)
> 	at com.conveyal.datatools.editor.controllers.api.EditorController.createOrUpdate(EditorController.java:479)
> 	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
> 	at spark.http.matching.Routes.execute(Routes.java:61)
> 	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
> 	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1598)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
> 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
> 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
> 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
> 	at java.base/java.lang.Thread.run(Thread.java:840)
> java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isNull()" because the return value of "java.util.List.get(int)" is null
> 	at com.conveyal.gtfs.loader.JdbcTableWriter.updateLinkedFields(JdbcTableWriter.java:344)
> 	at com.conveyal.gtfs.loader.JdbcTableWriter.updateChildTable(JdbcTableWriter.java:635)
> 	at com.conveyal.gtfs.loader.JdbcTableWriter.update(JdbcTableWriter.java:194)
> 	at com.conveyal.datatools.editor.controllers.api.EditorController.update(EditorController.java:499)
> 	at com.conveyal.datatools.editor.controllers.api.EditorController.createOrUpdate(EditorController.java:479)
> 	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
> 	at spark.http.matching.Routes.execute(Routes.java:61)
> 	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
> 	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1598)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
> 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
> 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
> 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
> 	at java.base/java.lang.Thread.run(Thread.java:840)**


> INFO  2024-05-01T15:17:04.668 [qtp1391483214-22] c.c.d.common.utils.SparkUtils(SparkUtils.java:136) Halting with status code 500.  Error message: An error was encountered while trying to save to the database
> ERROR 2024-05-01T15:17:04.669 [qtp1391483214-22] c.c.d.common.utils.SparkUtils(SparkUtils.java:139) An error was encountered while trying to save to the database
> WARN  2024-05-01T15:17:04.669 [qtp1391483214-22] c.c.d.manager.utils.ErrorUtils(ErrorUtils.java:64) Bugsnag not configured to report errors!
> INFO  2024-05-01T15:17:04.670 [qtp1391483214-22] c.c.d.common.utils.SparkUtils(SparkUtils.java:243) res (500) contact@xyz.xyz PUT: http://localhost:9966/api/editor/secure/pattern/2?feedId=08eb4bf1-524b-4776-99ef-ffa8ff5e1dc8&sessionId=node0vf9zz6fml5ufcl41gch62w41 
> {
>   "result" : "ERR",
>   "message" : "An error was encountered while trying to save to the database",
>   "code" : 500,
>   "detail" : "Cannot invoke \"com.fasterxml.jackson.databind.JsonNode.isNull()\" because the return value of \"java.util.List.get(int)\" is null"
> }
> `

**Comment by afconlab** [comment]
[https://github.com/ibi-group/datatools-server/issues/593](url)
