### ISSUE TITLE
Shape_dist_traveled is not adjusted when removing stop from pattern

### ISSUE THREAD

**Issue by fberci** [ibi-group/datatools-ui#941]
## Observed behavior

If you remove a stop from the beginning of the trip pattern using the UI, the `shape_dist_traveled` values will not be adjusted in `stop_times.txt`, even though the shape_dist_traveled values in `shapes.txt` do get updated. This results in a mismatch between the two values.

## Expected behavior

Values in `stop_times.txt::shape_dist_traveled` should get adjusted. The `shape_dist_traveled` of the new first stop should be 0, instead of its distance before the truncation.

## Steps to reproduce the problem

1. Create a trip pattern with several stops.
2. Create a trip using the trip pattern.
3. Remove stops from the beginning of the trip pattern. (E.g. remove the first two stops.)
4. Create a new snapshot and download the GTFS.

In the resulting GTFS:
 - `shapes.txt` will be filled out correctly, the first shape point will have 0 as `shape_dist_traveled`.
 - Howerver in `stop_times.txt` stops will have an incorrect `shape_dist_traveled value`. 

## Any special notes on configuration used

None.

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

datatools-ui version: `1be32bec`

**Comment by fberci** [comment]
If I would have to guess, a call to `assignDistancesToPatternStops()` is missing from [somewhere here](https://github.com/ibi-group/datatools-ui/blob/dev/lib/editor/actions/map/stopStrategies.js#L550-L552) (either in `removeStopFromPattern` or in `updatePatternStops`).

**Comment by philip-cline** [comment]
Hi @fberci I think your hunch is probably correct. We've been working on improving some existing bugs with shape_dist_traveled and shapes calculations lately in a series of PRs and this was one that was noted as well. I'll tag this issue when we've got a PR out for it.
